
require 'rake/clean'
require 'ffi'

FILES = {}

task :default => :build

def self.file_task(filename, opts, &block)
  name, dep = opts.is_a?(Hash) ? opts.to_a.first : [opts, nil]
  
  FILES[name] = filename
  CLEAN.include filename
  task name => filename
  
  if dep
    file filename => FILES[dep], &block
  else
    file filename, &block
  end
end

def cmd(string)
  fail "Command failed: #{string}" unless system(string)
end

file_task 'rabbitmq-c.tar.gz', :download_tarball do
  version = "0.6.0"
  release = "https://github.com/alanxz/rabbitmq-c/releases/download/v#{version}/rabbitmq-c-#{version}.tar.gz"
  cmd "wget #{release}"
  cmd "mv #{File.basename(release)} #{FILES[:download_tarball]}"
end

file_task 'rabbitmq-c', :download => :download_tarball do
  cmd "tar -xf #{FILES[:download_tarball]}"
  cmd "mv rabbitmq-c-* #{FILES[:download]}"
end

file_task 'config.status', :configure => :download do
  cmd "bash -c 'cd #{FILES[:download]} && ./configure'"
  cmd "cp #{FILES[:download]}/#{FILES[:configure]} ./"
end

file_task "librabbitmq.#{::FFI::Platform::LIBSUFFIX}", :build => :configure do
  cmd "bash -c 'cd #{FILES[:download]} && make'"
  cmd "cp #{FILES[:download]}/librabbitmq/.libs/#{FILES[:build]} ."
end
